kinda add clear value - fix not showing initial value - fixes #24
evandhq/react-persian-datepicker pull request #25
Opened 2017-02-28 20:33 UTC by pouriaMaleki

Clearly it's not a real fix for this problem. Just a hack to do it, It's on contributors to accept it as a fix.

The cleaner solution is to rewrite codes that setting `prop.value` to `state.value` (and something like this for `inputValue`) make clear difference between controlled and uncontrolled component usage (and also send a warning to developer if he changed component from controlled to uncontrolled or vice versa - like they did in [material-ui components](https://github.com/callemall/material-ui)) but since it's a major change it would be better to have milestone to do.

I should say thanks guys for bringing this component open source and I try to be available if any help needed.

2017-03-07 15:26 UTC, mohebifar requested changes

2017-03-07 15:26 UTC, mohebifar commented on examples/src/components/App.js
> +                x={true}
What is `x`?

2017-03-07 17:28 UTC, mohebifar approved these changes

2017-03-07 17:28 UTC, merged

2017-03-07 17:29 UTC, mohebifar commented
@pouriaMaleki Thank you! :+1:

2017-03-07 17:31 UTC, pouriaMaleki commented
Thanks for accepting, sorry for noobish prop left in example.

On Tue, Mar 7, 2017, 8:59 PM Mohamad Mohebifar <notifications@github.com>
wrote:

> @pouriaMaleki <https://github.com/pouriaMaleki> Thank you! 👍
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/evandhq/react-persian-datepicker/pull/25#issuecomment-284795435>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACHRqgMsm1VwmwA-DqOb09kJoI3R67Dvks5rjZPtgaJpZM4MO3Jv>
> .
>

2017-03-07 17:36 UTC, mohebifar commented
Haha, that's fine.

2017-05-23 13:04 UTC, pouriaMaleki commented
dude can you bump the version in npm?